.TH GITDATA 1 "gitdata manual"
.SH NAME
gitdata \- Fetch GitHub repository information including repo names, contributors, tags, and languages.


.SH DESCRIPTION
.B gitdata
is a command that retrieves information about a GitHub user's repositories, including contributors, tags, and languages.

.PP
This command prompts the user to enter a GitHub username, then fetches and displays information for each repository owned by that user.

.SH OPTIONS
.TP
.BI No \- options \- right \-  now

.SH To Run
To run the script:
.B
.BR gitdata
