.TH GITDATA 1 "gitdata manual"
.SH NAME
gitdata \- Fetch GitHub repository information including repo names, contributors, tags, and languages.


.SH DESCRIPTION
.B gitdata
is a command that retrieves information about a GitHub user's repositories, including contributors, tags, and languages.

.PP
This command prompts the user to enter a GitHub username, then fetches and displays information for each repository owned by that user.

.SH OPTIONS
.TP
.BI No \- options \- right \-  now

.SH To Run
To run the script:
.B
.BR gitdata
.TH GITDATA 1
.SH NAME
gitdata \- Fetch GitHub repository information including repo names, contributors, tags, and languages.


.SH DESCRIPTION
.B gitdata
is a command that retrieves information about a GitHub user's repositories, including contributors, tags, and languages.

.SH OPTIONS
.TP
.BI -h, --help
Display help and usage information.


.SH To Run
To run the script:
.B
.BR gitdata " <username>"


.SH AUTHOR
Written by Lokesh Dangi

.SH SEE ALSO
Online documentation at https://github.com/lokeshdangii/Own_Defined_Linux_Commands

.SH BUGS
Report bugs to https://github.com/lokeshdangii/Own_Defined_Linux_Commands/issues

.SH COPYRIGHT
This is a command built for personal use. See the source for copying conditions. There is NO
warranty; not even for DURABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH VERSION
1.0

.SH DATE
January 2024


